//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace authorization_sokolova_22._102
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public long user_id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string patronymic { get; set; }
        public long authorization_id { get; set; }
        public long role_id { get; set; }
    
        public virtual Authorizations Authorizations { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
